#!/usr/bin/env bun
/**
 * Generates src/themes.ts from the public shadcn registry only.
 *
 * Sources (in order per theme name):
 * 1. Embedded items in styles/new-york-v4/registry.json (type registry:theme)
 * 2. styles/new-york-v4/theme-{name}.json when present
 * 3. colors/{name}.json (inlineColors.light / dark)
 *
 * REGISTRY_URL — default https://ui.shadcn.com/r
 */

import { writeFileSync } from "fs";
import { join } from "path";

import { PRESET_THEMES } from "shadcn/preset";

type RegistryThemeItem = {
  name: string;
  title: string;
  type: "registry:theme";
  cssVars?: {
    light?: Record<string, string>;
    dark?: Record<string, string>;
    theme?: Record<string, string>;
  };
};

/** Run via `bun run generate:themes` from the package root so `src/themes.ts` resolves. */
const OUT = join(process.cwd(), "src/themes.ts");

const REGISTRY_URL = (process.env.REGISTRY_URL ?? "https://ui.shadcn.com/r").replace(/\/$/, "");

function capitalize(s: string) {
  return s.charAt(0).toUpperCase() + s.slice(1);
}

async function fetchJson(url: string): Promise<unknown> {
  const res = await fetch(url);
  if (!res.ok) {
    throw new Error(`GET ${url} → ${res.status} ${res.statusText}`);
  }
  return res.json();
}

async function tryFetchJson(url: string): Promise<unknown | null> {
  const res = await fetch(url);
  if (!res.ok) return null;
  return res.json();
}

type RegistryJson = {
  items?: Array<{
    name?: string;
    type?: string;
    cssVars?: RegistryThemeItem["cssVars"];
  }>;
};

function registryItemToTheme(item: {
  name: string;
  cssVars: NonNullable<RegistryThemeItem["cssVars"]>;
}): RegistryThemeItem {
  const shortName = item.name.replace(/^theme-/, "");
  return {
    name: shortName,
    title: capitalize(shortName),
    type: "registry:theme",
    cssVars: {
      ...(item.cssVars.theme ? { theme: item.cssVars.theme } : {}),
      light: item.cssVars.light ?? {},
      dark: item.cssVars.dark ?? {},
    },
  };
}

function colorsJsonToTheme(
  name: string,
  data: {
    inlineColors: { light: Record<string, string>; dark: Record<string, string> };
  },
): RegistryThemeItem {
  return {
    name,
    title: capitalize(name),
    type: "registry:theme",
    cssVars: {
      light: data.inlineColors.light,
      dark: data.inlineColors.dark,
    },
  };
}

function buildThemesMapFromRegistry(data: RegistryJson) {
  const map = new Map<string, RegistryThemeItem>();
  for (const item of data.items ?? []) {
    if (item.type !== "registry:theme" || !item.name || !item.cssVars) continue;
    if (!item.name.startsWith("theme-")) continue;
    const t = registryItemToTheme({
      name: item.name,
      cssVars: item.cssVars,
    });
    map.set(t.name, t);
  }
  return map;
}

function emitThemesFile(themes: RegistryThemeItem[]) {
  const header = `/** Auto-generated by scripts/generate-themes.ts — do not edit by hand. */

`;

  const body = `export type RegistryThemeItem = {
  name: string
  title: string
  type: "registry:theme"
  cssVars?: {
    light?: Record<string, string>
    dark?: Record<string, string>
    theme?: Record<string, string>
  }
}

export const THEMES: RegistryThemeItem[] = ${JSON.stringify(themes, null, 2)} as RegistryThemeItem[]
`;

  writeFileSync(OUT, header + body, "utf8");
}

async function main() {
  const registryUrl = `${REGISTRY_URL}/styles/new-york-v4/registry.json`;
  console.info(`Fetching ${registryUrl}`);
  const registry = (await fetchJson(registryUrl)) as RegistryJson;
  const fromRegistry = buildThemesMapFromRegistry(registry);

  const uniqueNames = Array.from(new Set(PRESET_THEMES as readonly string[]));
  const result: RegistryThemeItem[] = [];
  const missing: string[] = [];

  for (const name of uniqueNames) {
    if (fromRegistry.has(name)) {
      result.push(fromRegistry.get(name)!);
      continue;
    }

    const themeFileUrl = `${REGISTRY_URL}/styles/new-york-v4/theme-${name}.json`;
    const themeFileData = (await tryFetchJson(themeFileUrl)) as {
      name?: string;
      type?: string;
      cssVars?: RegistryThemeItem["cssVars"];
    } | null;

    if (
      themeFileData?.type === "registry:theme" &&
      themeFileData.cssVars?.light &&
      themeFileData.cssVars?.dark
    ) {
      const itemName = themeFileData.name ?? `theme-${name}`;
      result.push(
        registryItemToTheme({
          name: itemName.startsWith("theme-") ? itemName : `theme-${name}`,
          cssVars: themeFileData.cssVars as NonNullable<RegistryThemeItem["cssVars"]>,
        }),
      );
      continue;
    }

    const colorUrl = `${REGISTRY_URL}/colors/${name}.json`;
    const colorData = (await tryFetchJson(colorUrl)) as {
      inlineColors?: {
        light: Record<string, string>;
        dark: Record<string, string>;
      };
    } | null;

    if (colorData?.inlineColors?.light && colorData?.inlineColors?.dark) {
      result.push(colorsJsonToTheme(name, colorData as Parameters<typeof colorsJsonToTheme>[1]));
      continue;
    }

    missing.push(name);
  }

  if (missing.length > 0) {
    throw new Error(
      `Missing themes (not in registry.json, theme-*.json, or colors/*.json): ${missing.join(", ")}`,
    );
  }

  emitThemesFile(result);
  console.info(`Wrote ${result.length} themes → ${OUT}`);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
